AllCops:
  Excludes:
    - config/puma.rb
    - db/**
    - db/migrate/**
    - config/initializers/*.rb
    - config/environments/*.rb
    - Berksfile
    - recipes/basic.rb
    - attributes/*.rb
    - puma.rb

Rails:
 Enabled: true

# Customize rules
Metrics/LineLength:
  Max: 95

MethodLength:
  Max: 35

Metrics/AbcSize:
   Enabled: false

BlockLength:
  Max: 70

Documentation:
    Enabled: false
